name: build
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install (read-only)
        run: |
          npm ci --no-audit --no-fund
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Setup must not modify tracked files"; git status --porcelain; exit 1;
          fi
        working-directory: web
      - name: Lint
        run: npm run lint --if-present
      - name: Typecheck
        run: npm run typecheck --if-present
      - name: Build
        run: npm run build

  e2e:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install deps (app)
        run: npm ci --no-audit --no-fund
        working-directory: web

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: web

      - name: Typecheck
        run: npm run typecheck
        working-directory: web

      - name: Build
        run: npm run build
        working-directory: web

      - name: Run E2E tests
        run: npm run test:e2e
        working-directory: web

      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            web/playwright-report
            web/test-results
          retention-days: 7
