name: Create Tag (manual)
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (ex: 1.0.0). Laisser vide pour lire web/package.json'
        required: false
        type: string

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Determine version
        id: v
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            ver="${{ github.event.inputs.version }}"
          else
            ver=$(node -e "console.log(require('./web/package.json').version)")
          fi
          echo "Version: $ver"
          echo "ver=$ver" >> "$GITHUB_OUTPUT"
          echo "tag=v$ver" >> "$GITHUB_OUTPUT"

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create tag if missing
        shell: bash
        run: |
          set -euo pipefail
          tag="${{ steps.v.outputs.tag }}"
          echo "Target tag: $tag"
          if git rev-parse "$tag" >/dev/null 2>&1; then
            echo "Tag $tag already exists. Nothing to do."
            exit 0
          fi
          git tag "$tag" -m "Release $tag"
          git push origin "$tag"
          echo "Pushed $tag. The release workflow will start."
