name: Refresh web lockfile
on:
  workflow_dispatch: {}
jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install (generate lockfile)
        working-directory: web
        run: npm install --package-lock-only
      - name: Commit lockfile
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add web/package-lock.json
            git commit -m "chore(ci): refresh web/package-lock.json"
          fi
      - name: Push
        run: |
          git push
