name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install
        run: npm ci --no-audit --no-fund
      - name: Build
        run: npm run build
      - name: Zip dist
        run: zip -r dist.zip dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: web/dist.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: web/dist.zip
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

