name: release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag à relivrer (ex: v1.0.0). Laisser vide = utiliser le dernier tag.'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve tag (input or latest)
        id: r
        shell: bash
        run: |
          set -euo pipefail
          ref="${{ github.event.inputs.ref }}"
          if [[ -z "$ref" ]]; then
            ref=$(git describe --tags --abbrev=0 --match "v*")
          fi
          git checkout "$ref"
          echo "ref=$ref" >> "$GITHUB_OUTPUT"
          echo "Using ref: $ref"

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install deps
        run: npm ci
        working-directory: web

      - name: Build
        run: npm run build
        working-directory: web

      - name: Zip dist
        shell: bash
        run: |
          cd web
          zip -r "../web-dist-${{ steps.r.outputs.ref }}.zip" dist

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ steps.r.outputs.ref }}
          name: ${{ steps.r.outputs.ref }}
          files: |
            web-dist-${{ steps.r.outputs.ref }}.zip

