name: Supabase Migrations

on:
  push:
    paths:
      - 'supabase/**'
  workflow_dispatch:

jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
      - run: supabase db reset
      - run: supabase db push
